### ISSUE TITLE
Aerosol data not read correctly in WRF 

### ISSUE THREAD

**Issue by yoselita** [CORDEX-WRF-community/euro-cordex-cmip6#11] opened 2023-12-07 17:37 UTC
WRF does not read timestamps correctly in the aerosol files. This means that multiyear files for aerosols can be created and placed in WRF/run folder, and WRF will read correctly the aerosol file if the starting date of the simulations corresponds to the starting date of the aerosol file.  But when you restart you run, WRF will not look for the correct date in the aerosol file so that it corresponds to the new start of you simulation, but it will always read the first timestep of your aerosol file, no matter which the restart date it is.

**Comment by yoselita** [comment] 2023-12-07 17:38
A "quick fix" could be to place all the aerosol files you create in the WRF/run folder, and each time before you restart the run, you a script that will recreate a new aerosol file with the initial date that will correspond to the starting date of your restated simulations.

**Comment by jesusff** [comment] 2023-12-11 09:46
Duplicate of #6, which was solved

**Closed by jesusff** 2023-12-11 09:46 UTC
